---
# Group variables for webservers
apache_keepalive: "On"
apache_max_keepalive_requests: 150
apache_keepalive_timeout: 3
apache_server_tokens: "Prod"
apache_server_signature: "Off"
apache_trace_enable: "Off"
